package br.com.fatec.View;

import br.com.fatec.Controller.ExposicaoDAO;
import br.com.fatec.Model.Exposicao;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


public class ExposicaoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ExposicaoView
     */
    
    public void limparCampos() {
        txtNome.setText("");
        txtDataIni.setText("");
        txtDataFim.setText("");
        txtHoraIni.setText("");
        txtHoraFim.setText("");
        cmbTipo.setSelectedItem("TIPO");
        txtSalas.setText("");
        txtNome.grabFocus();
    }
    
    public ExposicaoView() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTExposicoes.getModel();
        jTExposicoes.setRowSorter(new TableRowSorter(modelo));
        readJTable();
        
    }
    
    public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) jTExposicoes.getModel();
        modelo.setNumRows(0);
        ExposicaoDAO dao = new ExposicaoDAO();
        for(Exposicao e: dao.read()) {
            modelo.addRow(new Object[] {
                e.getCodigoExpo(),
                e.getNome(),
                e.getDataIni(),
                e.getDataFim(),
                e.getHoraIni(),
                e.getHoraFim(),
                e.getTipo(),
                e.getSalas()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtDataIni = new javax.swing.JFormattedTextField();
        txtHoraIni = new javax.swing.JTextField();
        txtHoraFim = new javax.swing.JTextField();
        txtDataFim = new javax.swing.JFormattedTextField();
        txtSalas = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTExposicoes = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gerenciar exposição");

        jLabel1.setText("NOME DA EXPOSIÇÃO:");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIPO", "Temporária", "Permanente" }));
        cmbTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbTipoFocusLost(evt);
            }
        });
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        jLabel2.setText("DATA DE INÍCIO:");

        jLabel3.setText("HORA DE ABERTURA:");

        jLabel4.setText("DATA DO TÉRMINO:");

        jLabel5.setText("HORA DE FECHAMENTO:");

        jLabel6.setText("SALAS A SEREM RESERVADAS:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        try {
            txtDataIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataFim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDataFimFocusGained(evt);
            }
        });
        txtDataFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataFimActionPerformed(evt);
            }
        });

        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel7.setText("GERENCIAR EXPOSIÇÃO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(txtDataFim, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addComponent(txtDataIni))
                            .addComponent(jLabel1)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(txtHoraFim, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(txtHoraIni))
                                .addGap(18, 18, 18)
                                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHoraIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addComponent(txtHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExcluir)
                        .addComponent(btnCadastrar)))
                .addGap(25, 25, 25))
        );

        jTExposicoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Data do Início", "Data do Término", "Abertura", "Fechamento", "Tipo", "Salas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTExposicoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTExposicoesMouseClicked(evt);
            }
        });
        jTExposicoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTExposicoesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTExposicoes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        if(jTExposicoes.getSelectedRow() != -1) {
            Exposicao e = new Exposicao();
            ExposicaoDAO dao = new ExposicaoDAO();
            e.setNome(txtNome.getText());
            e.setDataIni(txtDataIni.getText());
            e.setDataFim(txtDataFim.getText());
            e.setHoraIni(txtHoraIni.getText());
            e.setHoraFim(txtHoraFim.getText());
            e.setTipo((String) cmbTipo.getSelectedItem());
            e.setSalas(txtSalas.getText());
            e.setCodigoExpo((int) jTExposicoes.getValueAt(jTExposicoes.getSelectedRow(), 0));
            
            dao.update(e);

            limparCampos();
            readJTable();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione a exposição que deseja atualizar!");
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Exposicao e = new Exposicao();
        ExposicaoDAO dao = new ExposicaoDAO();
        e.setNome(txtNome.getText());
        e.setDataIni(txtDataIni.getText());
        e.setDataFim(txtDataFim.getText());
        e.setHoraIni(txtHoraIni.getText());
        e.setHoraFim(txtHoraFim.getText());
        e.setTipo((String) cmbTipo.getSelectedItem());
        e.setSalas(txtSalas.getText());
        
        if (txtNome.getText().isEmpty() ||
                txtDataIni.getText().isEmpty() ||
                //txtDataFim.getText().isEmpty() ||
                txtHoraIni.getText().isEmpty() ||
                txtHoraFim.getText().isEmpty() ||
                cmbTipo.getSelectedItem() == "0" ||
                txtSalas.getText().isEmpty()) {
            
                    JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        } else {
            dao.create(e);
            limparCampos();
            readJTable();
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:
//        if(cmbTipo.getSelectedIndex() != 2) {
//            txtDataFim.setEditable(true);
//        } 
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        if(jTExposicoes.getSelectedRow() != -1) {
            Exposicao e = new Exposicao();
            ExposicaoDAO dao = new ExposicaoDAO();
            
            e.setCodigoExpo((int) jTExposicoes.getValueAt(jTExposicoes.getSelectedRow(), 0));
            
            dao.delete(e);

            limparCampos();
            readJTable();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione a exposição que deseja excluir!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jTExposicoesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTExposicoesKeyReleased
        // TODO add your handling code here:
        if(jTExposicoes.getSelectedRow() != -1) {
            limparCampos();
            txtNome.setText(jTExposicoes.getValueAt(jTExposicoes.getSelectedRow(), 1).toString());
            txtDataIni.setText(jTExposicoes.getValueAt(jTExposicoes.getSelectedRow(), 2).toString());
            txtDataFim.setText(jTExposicoes.getValueAt(jTExposicoes.getSelectedRow(), 3).toString());
            txtHoraIni.setText(jTExposicoes.getValueAt(jTExposicoes.getSelectedRow(), 4).toString());
            txtHoraFim.setText(jTExposicoes.getValueAt(jTExposicoes.getSelectedRow(), 5).toString());
            cmbTipo.setSelectedItem(jTExposicoes.getValueAt(jTExposicoes.getSelectedRow(), 6).toString());
            txtSalas.setText(jTExposicoes.getValueAt(jTExposicoes.getSelectedRow(), 7).toString());
        }
    }//GEN-LAST:event_jTExposicoesKeyReleased

    private void jTExposicoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTExposicoesMouseClicked
        // TODO add your handling code here:
        if(jTExposicoes.getSelectedRow() != -1) {
            limparCampos();
            txtNome.setText(jTExposicoes.getValueAt(jTExposicoes.getSelectedRow(), 1).toString());
            txtDataIni.setText(jTExposicoes.getValueAt(jTExposicoes.getSelectedRow(), 2).toString());
            txtDataFim.setText(jTExposicoes.getValueAt(jTExposicoes.getSelectedRow(), 3).toString());
            txtHoraIni.setText(jTExposicoes.getValueAt(jTExposicoes.getSelectedRow(), 4).toString());
            txtHoraFim.setText(jTExposicoes.getValueAt(jTExposicoes.getSelectedRow(), 5).toString());
            cmbTipo.setSelectedItem(jTExposicoes.getValueAt(jTExposicoes.getSelectedRow(), 6).toString());
            txtSalas.setText(jTExposicoes.getValueAt(jTExposicoes.getSelectedRow(), 7).toString());
        }
    }//GEN-LAST:event_jTExposicoesMouseClicked

    private void cmbTipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbTipoFocusLost
        // TODO add your handling code here:
//        if (cmbTipo.getSelectedIndex() == 2) {
//            txtDataFim.setEnabled(false);
//        }
    }//GEN-LAST:event_cmbTipoFocusLost

    private void txtDataFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataFimActionPerformed

    private void txtDataFimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataFimFocusGained
        // TODO add your handling code here:
//        if(cmbTipo.getSelectedIndex() == 2) {
//            txtDataFim.setEnabled(false);
//        }
    }//GEN-LAST:event_txtDataFimFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTExposicoes;
    private javax.swing.JFormattedTextField txtDataFim;
    private javax.swing.JFormattedTextField txtDataIni;
    private javax.swing.JTextField txtHoraFim;
    private javax.swing.JTextField txtHoraIni;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSalas;
    // End of variables declaration//GEN-END:variables
}
